imports:
    - { resource: config_dev.yml }
    - { resource: "@TactDoryBundle/Resources/config/config_test.yml" } ## Don't modify this import.

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
